import OpenAI from "openai";
import { NextResponse } from "next/server";

import {
  generateSuggestedTasks,
  generateSuggestionCards,
} from "@/lib/ai/mockSuggestions";
import type { AISuggestionsResponse, SuggestedTaskDraft, SuggestionCard } from "@/lib/ai/types";
import type { Task } from "@/types/task";

const DEFAULT_MODEL = process.env.OPENAI_MODEL ?? "gpt-5.2";

const SYSTEM_PROMPT = `You are a planning assistant for a productivity app.
Return strict JSON only with this shape:
{
  "cards": [{"title": string, "body": string}],
  "suggestedTasks": [{"title": string, "notes": string, "cadence": "daily"|"weekly"|"monthly", "priority": "low"|"medium"|"high", "deadline": "YYYY-MM-DD"}]
}
Rules:
- cards must include exactly 4 items with titles: Rewrite Goal, Break Into Steps, What To Do First, Priority Order.
- suggestedTasks must have 1-6 concise actionable tasks.
- deadlines should be realistic and near-term.
- no markdown, no code fences, only JSON.`;

function sanitizeJsonText(raw: string): string {
  return raw.replace(/```json|```/g, "").trim();
}

function normalizeCard(card: unknown): SuggestionCard | null {
  if (!card || typeof card !== "object") {
    return null;
  }

  const candidate = card as Partial<SuggestionCard>;
  if (typeof candidate.title !== "string" || typeof candidate.body !== "string") {
    return null;
  }

  return {
    title: candidate.title.trim(),
    body: candidate.body.trim(),
  };
}

function normalizeTaskDraft(task: unknown): SuggestedTaskDraft | null {
  if (!task || typeof task !== "object") {
    return null;
  }

  const candidate = task as Partial<SuggestedTaskDraft>;
  const cadence =
    candidate.cadence === "daily" || candidate.cadence === "weekly" || candidate.cadence === "monthly"
      ? candidate.cadence
      : null;
  const priority =
    candidate.priority === "low" || candidate.priority === "medium" || candidate.priority === "high"
      ? candidate.priority
      : null;

  if (!cadence || !priority || typeof candidate.title !== "string") {
    return null;
  }

  const deadline = typeof candidate.deadline === "string" && candidate.deadline.trim() ? candidate.deadline : undefined;

  return {
    title: candidate.title.trim(),
    notes: typeof candidate.notes === "string" ? candidate.notes.trim() : "Generated by OpenAI planning assistant.",
    cadence,
    priority,
    deadline,
  };
}

function fallbackResponse(prompt: string, tasks: Task[], notice?: string): AISuggestionsResponse {
  return {
    cards: generateSuggestionCards(prompt, tasks),
    suggestedTasks: generateSuggestedTasks(prompt),
    source: "mock",
    notice,
  };
}

function getOpenAIErrorNotice(error: unknown): string {
  if (error && typeof error === "object") {
    const candidate = error as { status?: number; code?: string; message?: string };
    const statusText = typeof candidate.status === "number" ? `status ${candidate.status}` : "request error";
    const codeText = typeof candidate.code === "string" ? candidate.code : "unknown";
    const messageText = typeof candidate.message === "string" ? candidate.message : "No details available.";
    return `OpenAI request failed (${statusText}, code: ${codeText}). ${messageText}`;
  }

  if (error instanceof Error) {
    return `OpenAI request failed. ${error.message}`;
  }

  return "OpenAI request failed. Showing local planning suggestions.";
}

export async function POST(request: Request) {
  const body = (await request.json().catch(() => null)) as
    | { prompt?: string; tasks?: Task[] }
    | null;

  const prompt = body?.prompt?.trim() || "";
  const tasks = Array.isArray(body?.tasks) ? body.tasks : [];

  if (!prompt) {
    return NextResponse.json(fallbackResponse("", tasks, "Missing prompt, used local planner."));
  }

  const apiKey = process.env.OPENAI_API_KEY?.trim();
  const isPlaceholderKey =
    !apiKey ||
    apiKey === "your_api_key_here" ||
    apiKey === "paste_your_openai_api_key_here" ||
    apiKey.toLowerCase().includes("your_api_key");

  if (isPlaceholderKey) {
    return NextResponse.json(
      fallbackResponse(prompt, tasks, "OPENAI_API_KEY is missing. Showing local planning suggestions."),
    );
  }

  try {
    const client = new OpenAI({ apiKey });

    const response = await client.responses.create({
      model: DEFAULT_MODEL,
      input: [
        {
          role: "system",
          content: [{ type: "input_text", text: SYSTEM_PROMPT }],
        },
        {
          role: "user",
          content: [
            {
              type: "input_text",
              text: JSON.stringify({
                prompt,
                tasks: tasks.map((task) => ({
                  title: task.title,
                  priority: task.priority,
                  deadline: task.deadline,
                  completed: task.completed,
                })),
              }),
            },
          ],
        },
      ],
      max_output_tokens: 1200,
    });

    const parsed = JSON.parse(sanitizeJsonText(response.output_text || "{}")) as {
      cards?: unknown[];
      suggestedTasks?: unknown[];
    };

    const cards = Array.isArray(parsed.cards)
      ? parsed.cards.map(normalizeCard).filter((item): item is SuggestionCard => Boolean(item))
      : [];
    const suggestedTasks = Array.isArray(parsed.suggestedTasks)
      ? parsed.suggestedTasks
          .map(normalizeTaskDraft)
          .filter((item): item is SuggestedTaskDraft => Boolean(item))
          .slice(0, 6)
      : [];

    if (cards.length < 4 || suggestedTasks.length === 0) {
      return NextResponse.json(
        fallbackResponse(prompt, tasks, "Model response was incomplete. Fallback suggestions were used."),
      );
    }

    return NextResponse.json({
      cards,
      suggestedTasks,
      source: "openai",
    } satisfies AISuggestionsResponse);
  } catch (error) {
    return NextResponse.json(
      fallbackResponse(prompt, tasks, getOpenAIErrorNotice(error)),
    );
  }
}
